// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC94COy8KYkrMT6zjhbzfS3JaYZo8-H7dM',
    appId: '1:27878167844:web:ad1f49c7e2d10b30e90fb1',
    messagingSenderId: '27878167844',
    projectId: 'laptopharbour-948bf',
    authDomain: 'laptopharbour-948bf.firebaseapp.com',
    storageBucket: 'laptopharbour-948bf.firebasestorage.app',
    measurementId: 'G-FD4FLTEJGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLLZRlpebyuNWcKU45DQC6loNLTpsa0wE',
    appId: '1:27878167844:android:9e313b1f3f2e130ae90fb1',
    messagingSenderId: '27878167844',
    projectId: 'laptopharbour-948bf',
    storageBucket: 'laptopharbour-948bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMZ1rva-Q2mZTeEfX11_W0ZKS1uA9YaQY',
    appId: '1:27878167844:ios:2e20938356bcf26ee90fb1',
    messagingSenderId: '27878167844',
    projectId: 'laptopharbour-948bf',
    storageBucket: 'laptopharbour-948bf.firebasestorage.app',
    iosBundleId: 'com.example.eprojectSem4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMZ1rva-Q2mZTeEfX11_W0ZKS1uA9YaQY',
    appId: '1:27878167844:ios:2e20938356bcf26ee90fb1',
    messagingSenderId: '27878167844',
    projectId: 'laptopharbour-948bf',
    storageBucket: 'laptopharbour-948bf.firebasestorage.app',
    iosBundleId: 'com.example.eprojectSem4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC94COy8KYkrMT6zjhbzfS3JaYZo8-H7dM',
    appId: '1:27878167844:web:c0de882d30b39af9e90fb1',
    messagingSenderId: '27878167844',
    projectId: 'laptopharbour-948bf',
    authDomain: 'laptopharbour-948bf.firebaseapp.com',
    storageBucket: 'laptopharbour-948bf.firebasestorage.app',
    measurementId: 'G-SESGQTZEHR',
  );
}
